// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "CodeCollab Viewer",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "CodeCollab Viewer",
            targets: ["AppModule"],
            bundleIdentifier: "io.codecollab.cc-viewer",
            teamIdentifier: "XL5JK4F896",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/kishanraja/FloatingLabelTextFieldSwiftUI", "4.2.1"..<"5.0.0"),
        .package(url: "https://github.com/tichise/MaterialDesignSymbol.git", "2.8.5"..<"3.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "FloatingLabelTextFieldSwiftUI", package: "FloatingLabelTextFieldSwiftUI"),
                .product(name: "MaterialDesignSymbol", package: "MaterialDesignSymbol")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)